import SwiftUI

/// UserDefaults keys for display preferences, read with `@AppStorage`.
enum AppPreferences {
    static let showCategoryIconsKey = "showCategoryIcons"
    static let categoryPickerStyleKey = "categoryPickerStyle"
    static let saveLocationKey = "saveTransactionLocation"
}

// MARK: - Localization

extension String {
    /// Looks the string up in Localizable.strings; returns it unchanged if there's no translation.
    var localized: String {
        NSLocalizedString(self, comment: "")
    }

    func localizedFormat(_ arguments: CVarArg...) -> String {
        String(format: NSLocalizedString(self, comment: ""), arguments: arguments)
    }
}

// MARK: - Category picker

enum CategoryPickerStyle: String, CaseIterable, Identifiable {
    /// Horizontal scrolling row of all categories.
    case carousel
    /// Three categories plus "⋯" that expands the full grid in place.
    case grid

    var id: String { rawValue }

    var title: String {
        switch self {
        case .carousel: return "Carousel".localized
        case .grid: return "Compact grid".localized
        }
    }
}

// MARK: - Theme

enum ThemeManager {
    /// Sets the style on the windows directly: `.preferredColorScheme(nil)` doesn't reliably
    /// switch back to the system appearance after Light/Dark was chosen.
    static func apply(_ theme: AppTheme) {
        let style: UIUserInterfaceStyle
        switch theme {
        case .light: style = .light
        case .dark: style = .dark
        case .system: style = .unspecified
        }

        for scene in UIApplication.shared.connectedScenes {
            guard let windowScene = scene as? UIWindowScene else { continue }
            for window in windowScene.windows {
                window.overrideUserInterfaceStyle = style
            }
        }
    }
}

// MARK: - App icon

/// Color style of the app icon. Each style exists with every glyph in Assets.xcassets
/// (generated by tools/generate_icons.py).
enum AppIconStyle: String, CaseIterable, Identifiable {
    case classic = "Classic"
    case midnight = "Midnight"
    case emerald = "Emerald"
    case sunset = "Sunset"
    case minimal = "Minimal"

    var id: String { rawValue }

    var title: String { rawValue.localized }
}

/// Symbol on the app icon: a neutral wallet, or the sign of the selected currency.
enum AppIconGlyph: String {
    case neutral = "Neutral"
    case tenge = "Tenge"
    case ruble = "Ruble"
    case dollar = "Dollar"
    case euro = "Euro"

    /// Currencies without their own icon use the wallet.
    static func forCurrency(_ code: String) -> AppIconGlyph {
        switch code {
        case "KZT": return .tenge
        case "RUB": return .ruble
        case "USD": return .dollar
        case "EUR": return .euro
        default: return .neutral
        }
    }
}

enum AppIconManager {
    static let styleKey = "appIconStyle"
    static let matchCurrencyKey = "appIconMatchesCurrency"

    static var style: AppIconStyle {
        AppIconStyle(rawValue: UserDefaults.standard.string(forKey: styleKey) ?? "") ?? .classic
    }

    static var matchesCurrency: Bool {
        UserDefaults.standard.bool(forKey: matchCurrencyKey)
    }

    static func glyph(matchesCurrency: Bool = AppIconManager.matchesCurrency) -> AppIconGlyph {
        matchesCurrency ? .forCurrency(AppCurrency.code) : .neutral
    }

    /// `nil` is the primary "AppIcon" (Classic + wallet).
    static func iconName(style: AppIconStyle, glyph: AppIconGlyph) -> String? {
        if style == .classic && glyph == .neutral { return nil }
        return "AppIcon-\(style.rawValue)-\(glyph.rawValue)"
    }

    static func previewImage(style: AppIconStyle, glyph: AppIconGlyph) -> String {
        "IconPreview-\(style.rawValue)-\(glyph.rawValue)"
    }

    /// Sets the icon from the saved style, the "match currency" switch and the current currency.
    /// iOS shows its own "You have changed the icon" alert whenever the icon actually changes.
    static func applyCurrent(completion: ((Error?) -> Void)? = nil) {
        let name = iconName(style: style, glyph: glyph())
        guard UIApplication.shared.supportsAlternateIcons,
              UIApplication.shared.alternateIconName != name else {
            completion?(nil)
            return
        }
        UIApplication.shared.setAlternateIconName(name) { error in
            DispatchQueue.main.async {
                completion?(error)
            }
        }
    }
}
